import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowUpRight,ChevronLeft,Menu,X,Plus,Trash2}from'lucide-react';
import'./styles.css';
const BOOK='https://tally.so/r/686Gdk',IG='https://www.instagram.com/lucidblvck.ttt/';
const seed=[['96e043e5-6142-44b7-8657-c4108d14adf7','Necroform II'],['52cd083b-05c0-4fde-9a67-2ed0d52e3ba2','Necroform I'],['f669516e-4ee0-4299-b777-43ba87b569d1','Kitty'],['01a8d64b-266d-45f4-8248-89bd70d310f3','Lady'],['a137cfc5-cf6f-43f9-8237-a408befac9f8','Demon lady'],['55a810c6-8da3-4d05-9c24-6f7a98a2722b','Mask'],['1a2c974e-28de-4253-95b1-75f8d4795147','Parasite'],['5acaf33d-9a9f-496c-b785-33a1f3c215a3','All seeing'],['3fbc759e-f759-4e60-ad23-cf0fd3098fa1','Thorned soul'],['674f8fa5-a58c-4203-aa70-269967d277da','Flowers'],['91f248ec-9ce1-4f74-91c7-b9866adbe9c4','Blackwork flower'],['ddf24868-0778-425b-b13b-4f33e60e38fa','Small ornamental'],['b573f0ac-583a-431f-8cca-f05e4919ef1c','Small ornamental'],['011617f6-6a85-487e-8564-18ecc0b7a353','Ornament'],['ee7944d1-80d9-4a0b-8e71-b6aaa04a1bd3','Berries']].map(([id,title])=>({id,title,price:'On request',size:id.startsWith('01a8')?'min. 25cm x 20cm':'On request',status:'Available',image:`/images/flash/${id}.webp`}));
const load=()=>{try{return JSON.parse(localStorage.getItem('lucid-flash'))||seed}catch{return seed}};
function go(path){history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'));scrollTo(0,0)}
function Link({to,children,className=''}){return <a href={to} className={className} onClick={e=>{if(to.startsWith('/')){e.preventDefault();go(to)}}}>{children}</a>}
function Header(){const[o,setO]=useState(false);return <header><Link to="/" className="wordmark">LUCID BLVCK<sup>®</sup></Link><button className="menu" onClick={()=>setO(!o)} aria-label="Menu">{o?<X/>:<Menu/>}</button><nav className={o?'open':''}><Link to="/flash">Flash</Link><Link to="/#about">About</Link><a className="nav-cta" href={BOOK}>Book a tattoo <ArrowUpRight/></a></nav></header>}
function Footer({flash=false}){return <footer><span>© 2026 LUCID BLVCK</span><img src="/images/lucid-blvck-mark-white.png" alt="Lucid Blvck"/><a href="#top">{flash?'All flash':'Back to top'} ↑</a></footer>}
function Card({x}){return <Link to={`/flash/${x.id}`} className="card"><div className="card-img"><img src={x.image} alt={`Flash design ${x.title}`}/></div><div><h2>{x.title}</h2><span>{x.status}</span></div></Link>}
function Home({items}){return <main id="top"><section className="hero"><div className="micro"><span>Kasterlee, Belgium</span><span>Private studio · Appointment only</span></div><h1>Custom <em>dark work.</em></h1><p>Blackwork, illustrative<br/>and ornamental tattooing.</p><a href="#flash-preview" className="down">Available flash ↓</a></section><section id="about" className="about"><p className="eyebrow">About the artist</p><div className="about-grid"><figure><img src="/images/about-bo.webp" alt="Bo, tattoo artist behind Lucid Blvck"/></figure><div><h2>Intentional tattoos<br/>with a <em>darker edge.</em></h2><p>Tattoo artist based in Kasterlee, Belgium, with a focus on blackwork, illustrative and ornamental work.</p><p>My style is inspired by darker imagery and organic shapes.</p><p>I enjoy creating custom tattoos that complement the natural flow of the body. From smaller tattoos to larger projects, I like each design to feel intentional and personal to the person wearing it.</p><p>I work from a private studio in Kasterlee, by appointment only. This allows me to offer a calm, relaxed and personal setting, with plenty of time and attention dedicated to your tattoo experience.</p></div></div></section><section id="flash-preview" className="section"><div className="section-head"><p className="eyebrow">Available flash</p><Link to="/flash">View all designs <ArrowUpRight/></Link></div><div className="grid preview">{items.slice(0,3).map(x=><Card key={x.id} x={x}/>)}</div><Link to="/flash" className="wide-link">View all available flash <ArrowUpRight/></Link></section><section className="instagram"><div><p className="eyebrow">Latest on Instagram</p><a href={IG}>@lucidblvck.ttt <ArrowUpRight/></a></div><div className="insta-grid"><iframe src="https://www.instagram.com/p/DcqdkFRDCka/embed" title="Instagram 1"/><iframe src="https://www.instagram.com/p/DbQmB57jNM-/embed" title="Instagram 2"/><iframe src="https://www.instagram.com/p/DbJVbl2jNeM/embed" title="Instagram 3"/></div><a href={IG} className="wide-link">Follow on Instagram <ArrowUpRight/></a></section><section className="cta"><p className="eyebrow">Have an idea?</p><h2>Let’s make<br/><em>something yours.</em></h2><a href={BOOK}>Start your booking <ArrowUpRight/></a><p>Complete the booking form to share your tattoo idea.</p><small>Appointments on selected days · Kasterlee, Belgium</small></section><Footer/></main>}
function Flash({items}){return <main id="top"><section className="page-hero"><div className="micro"><span>Available designs</span><span>Kasterlee, Belgium</span></div><h1>Available <em>flash.</em></h1><Link to="/" className="back"><ChevronLeft/> Back home</Link></section><section className="section"><div className="section-head"><p className="eyebrow">All flash</p><span>{items.length} designs</span></div><div className="grid">{items.map(x=><Card key={x.id} x={x}/>)}</div></section><section className="claim"><p className="eyebrow">Found your piece?</p><h2>Claim your <em>flash.</em></h2><a href={BOOK}>Start your booking <ArrowUpRight/></a></section><Footer flash/></main>}
function Detail({item}){if(!item)return <Missing/>;return <main id="top"><article className="detail"><div className="detail-image"><img src={item.image} alt={item.title}/></div><div className="detail-copy"><Link to="/flash" className="back"><ChevronLeft/> All flash</Link><p className="eyebrow">Lucid Blvck · Available design</p><h1>{item.title}</h1><dl><div><dt>Estimated price</dt><dd>{item.price}</dd></div><div><dt>Size</dt><dd>{item.size}</dd></div><div><dt>Status</dt><dd>{item.status}</dd></div></dl><a href={BOOK} className="book">Book this flash <ArrowUpRight/></a></div></article><Footer flash/></main>}
function Admin({items,setItems}){const[t,setT]=useState('');const add=e=>{e.preventDefault();if(!t)return;setItems([{id:`local-${Date.now()}`,title:t,price:'On request',size:'On request',status:'Available',image:'/images/lucid-blvck-mark-black.png'},...items]);setT('')};return <main className="admin"><section><p className="eyebrow">Local reconstruction</p><h1>Manage flash.</h1><p className="notice">Changes here are stored only in this browser. Connect secure login, a database and file storage before publishing this route as a real admin panel.</p><form onSubmit={add}><label>Title<input value={t} onChange={e=>setT(e.target.value)} placeholder="Design title"/></label><button><Plus/> Add flash</button></form><div className="admin-list">{items.map(x=><div key={x.id}><img src={x.image} alt=""/><span>{x.title}</span><button aria-label={`Delete ${x.title}`} onClick={()=>setItems(items.filter(i=>i.id!==x.id))}><Trash2/></button></div>)}</div></section></main>}
function Missing(){return <main className="missing"><h1>Page not found.</h1><Link to="/">Back home</Link></main>}
function App(){const[path,setPath]=useState(location.pathname),[items,setState]=useState(load);useEffect(()=>{const f=()=>setPath(location.pathname);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);const setItems=x=>{setState(x);localStorage.setItem('lucid-flash',JSON.stringify(x))};const page=useMemo(()=>path==='/'?<Home items={items}/>:path==='/flash'?<Flash items={items}/>:path==='/admin/flash'?<Admin items={items} setItems={setItems}/>:path.startsWith('/flash/')?<Detail item={items.find(x=>x.id===path.split('/').pop())}/>:<Missing/>,[path,items]);return <><Header/>{page}</>}
createRoot(document.getElementById('root')).render(<App/>);
